# Generated by Django 3.1.7 on 2021-04-11 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.FileField(default='', upload_to='video/thumbnail')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='Enter description')),
                ('genre', models.ManyToManyField(to='main.Genres')),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'titles',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ova', 'OVA'), ('tv', 'TV'), ('ona', 'ONA'), ('special', 'SPECIAL')], default='tv', max_length=8)),
                ('episode', models.IntegerField(default=1)),
                ('season', models.IntegerField(default=1)),
                ('language', models.CharField(choices=[('sub', 'SUB'), ('dub', 'DUB')], default='sub', max_length=6)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(default='', upload_to='video/uploaded/series')),
                ('views', models.IntegerField(default=0)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.titles')),
            ],
            options={
                'verbose_name': 'series',
                'verbose_name_plural': 'series',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movies_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='movie', editable=False, max_length=6)),
                ('language', models.CharField(choices=[('sub', 'SUB'), ('dub', 'DUB')], default='sub', max_length=6)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(default='', upload_to='video/uploaded/movies')),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.titles')),
            ],
            options={
                'verbose_name': 'movies',
                'verbose_name_plural': 'movies',
            },
        ),
    ]
