# Generated by Django 3.1.7 on 2021-04-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='video/thumbnail'),
        ),
    ]
