# Generated by Django 3.1.7 on 2021-04-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210412_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(default='Enter description', max_length=1000),
        ),
    ]
