# Generated by Django 3.1.7 on 2021-05-01 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210429_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watched',
            name='anime',
        ),
        migrations.AddField(
            model_name='watched',
            name='animeMovie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.movies'),
        ),
        migrations.AddField(
            model_name='watched',
            name='animeSeries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.series'),
        ),
    ]
