# Generated by Django 3.1.7 on 2021-05-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210501_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watched',
            old_name='series',
            new_name='serie',
        ),
    ]
